Image optimization
laptou/step pull request #12
Opened 2020-06-01 19:12 UTC by laptou

- Add image compression via Webpack to reduce page load time
- Turn JPEGs into progressive JPEGs via Webpack to reduce perceived page load time
- Generate several sizes of food images via Webpack to allow browser to select an image that is only as large as is necessary, reducing page load time

No screenshot because visually, this looks exactly the same as #11, but it loads almost twice as fast.

2020-06-01 22:23 UTC, jpnickolas requested changes
Will wait on #10 and #11 to get merged in before approving, but overall lgtm

2020-06-01 22:23 UTC, geekster777 commented on portfolio/src/main/client/src/components/sections/cooking.ts
> +    const src = require(`@res/img/dish/${info.attributes.image}?responsive&sizes[]=200,sizes[]=400,sizes[]=600`);
nit: this is more than 80 characters. You can just make this 2 strings you truncate together to keep you under 80 chars.

2020-06-02 21:46 UTC, jpnickolas requested changes

2020-06-02 21:46 UTC, geekster777 commented on portfolio/src/main/client/src/components/controls/lightbox.ts
> +  if (e.keyCode !== 27) return;
`KeyboardEvent.keyCode` is deprecated. Use `KeyboardEvent.key` instead:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keycode

2020-06-02 22:07 UTC, jpnickolas approved these changes

2020-06-02 22:18 UTC, jessicaslaughter approved these changes

2020-06-02 22:19 UTC, merged