Add DELETE method to comment API
laptou/step pull request #24
Opened 2020-06-04 15:31 UTC by laptou

Add DELETE method to comment API

2020-06-04 16:56 UTC, jpnickolas requested changes

2020-06-04 16:56 UTC, geekster777 commented on portfolio/src/main/java/com/google/sps/servlets/CommentServlet.java
> +    if (true) {
nit: to make the intention here more clear, use a variable:
```
// TODO implement authentication
boolean authenticated = false;
if (!authenticated) {
  // 401 error
}
```

2020-06-04 20:33 UTC, jessicaslaughter approved these changes

2020-06-05 01:03 UTC, jpnickolas approved these changes

2020-06-08 14:24 UTC, merged