Add more advanced styles
laptou/step pull request #6
Opened 2020-05-26 22:20 UTC by laptou

Add more advanced styles to make the page look prettier, including changing the font families and highlight colours to be consistent w/ my resume, and giving the food sections a more interesting layout.

![image](https://user-images.githubusercontent.com/14832331/82955867-a0756d00-9f7d-11ea-9ea2-ba605b0f29cf.png)

This closes #5.

2020-05-27 18:15 UTC, geekster777 commented
LGTM. Nice use of grid styles. Will approve once parent PR's are merged.

2020-05-27 23:05 UTC, jessicaslaughter approved these changes

2020-05-27 23:28 UTC, jpnickolas requested changes

2020-05-27 23:28 UTC, jpnickolas commented on portfolio/src/main/webapp/style.css
> +  color: hsl(0, 75%, 50%);
nit: comment what color these are since hsl (and honestly even hex colors that aren't white or black) are hard to read.

2020-05-28 16:23 UTC, jpnickolas approved these changes

2020-05-28 16:39 UTC, merged