Add dark mode
laptou/step pull request #7
Opened 2020-05-26 23:02 UTC by laptou

Add a dark mode that the user can toggle dynamically using a button in the header.

![image](https://user-images.githubusercontent.com/14832331/82958413-542d2b80-9f83-11ea-9df4-3b8eb108fc60.png)
![image](https://user-images.githubusercontent.com/14832331/82958429-5becd000-9f83-11ea-8735-a42fb5b5724e.png)

2020-05-28 18:14 UTC, jessicaslaughter commented
This mostly looks good to me, but will wait on the merge conflicts to be resolved before reviewing so it's easier to see what changes are being made.

2020-05-28 19:51 UTC, laptou commented
Fixed it

2020-05-28 19:52 UTC, laptou commented on portfolio/src/main/webapp/index.html
> +  <body>
This is just an indentation change

2020-05-28 20:19 UTC, jpnickolas requested changes

2020-05-28 20:19 UTC, jpnickolas commented on portfolio/src/main/webapp/style.css
> +  border: 1pt currentColor dashed;
currentColor works here, but may become more difficult to juggle in more complicated pages. Consider using css variables if things get more complicated:
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2020-05-28 20:19 UTC, jpnickolas commented on portfolio/src/main/webapp/script.js
> + * @param {ThemeMode} mode
nit: add a description of what the function does.

2020-05-28 20:19 UTC, jpnickolas commented on portfolio/src/main/webapp/script.js
> +  console.debug(`changing theme to ${mode}`);
Remove debug statements.

2020-05-28 20:19 UTC, jpnickolas commented on portfolio/src/main/webapp/script.js
> +  state.theme.el.href = `/style.${mode}.css`;
Instead of loading new stylesheets every time a user toggles the theme, instead load all themes initially (still in separate files if you'd like) but hide dark mode behind a class that you can toggle.

2020-05-28 20:19 UTC, jpnickolas commented on portfolio/src/main/webapp/script.js
> +    .addEventListener('click', toggleTheme);
nit: add a newline at the end of the file.

2020-05-28 20:19 UTC, jpnickolas commented on portfolio/src/main/webapp/script.js
> +let state = {
wrap your file in an anonymous function to keep state from leaking globally:
```
(function() {
  let themeMode = 'light';
  ...
})();
```

2020-05-28 20:20 UTC, geekster777 commented
Rip, looks like I never hit submit on my review here yesterday.

2020-05-28 20:43 UTC, jessicaslaughter requested changes

2020-05-28 20:43 UTC, jessicaslaughter commented on portfolio/src/main/webapp/index.html
> +      <div class='cooking-dish'>
Attributes should use double quotes. Same for other instances.

2020-05-28 20:43 UTC, jessicaslaughter commented on portfolio/src/main/webapp/index.html
> +            spot,
nit: it looks like the text here got put on a new line, but can be moved back up (same with paragraphs below)

2020-05-28 23:34 UTC, jessicaslaughter approved these changes

2020-05-29 16:33 UTC, jpnickolas requested changes

2020-05-29 16:33 UTC, geekster777 commented on portfolio/src/main/webapp/index.html
> +    <link rel="stylesheet" href="style.dark.css" id="theme-link" >
Remove the duplicate id's.

2020-05-29 17:27 UTC, jpnickolas approved these changes

2020-05-29 17:36 UTC, merged